### ISSUE TITLE
(Summary) Meets Expectations

### ISSUE THREAD

**Issue by CharlesDLandau** [sduttonpro/sduttonpro.github.io#1]
Overall your work looks correct - the only place where I identified you missing the spec is the navigation in the top bar. You have good comments and structure in your HTML, and your CSS is written with good naming and organization.

In terms of improvement, I think that testing-driving the page before submitting it would have helped you out. One place I noticed that you hadn't met the spec involved navigating to the different sections using the links in the top bar. With some quick edits to your index.html file, I think you could have fixed this before submitting it.

If you want to dig deeper on this project besides with the navigation, you can play around with some of the settings in your CSS and "poke around." You're comfortable enough now with the basics of writing CSS that you can experiment.

Overall grade - Meets Expectations

**Comment by sduttonpro** [comment]
Thanks for the feedback Charles I'll ensure that navs in future projects link to the appropriate places on the website. It was an oversight on my part meant to go back to it once everything was fleshed out but neglected too. I'll make sure to test better in the future.
